default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: mukul
  host: localhost

development:
  <<: *default
  database: rails_demo

test:
  <<: *default
  database: rails_demo

staging:
  <<: *default
  database: rails_demo

production:
  <<: *default
  database: rails_demo
